# Generated by Django 4.0 on 2023-09-07 14:20

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("admins", "0001_initial"),
        ("client", "0002_alter_clientmodel_expires_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("released_date", models.DateField()),
                ("edition", models.CharField(max_length=50)),
                ("reserved_date_time", models.DateTimeField(blank=True, null=True)),
                (
                    "inserted_date_time",
                    models.DateTimeField(
                        default=datetime.datetime(2023, 9, 7, 14, 20, 12, 418493)
                    ),
                ),
                (
                    "inserted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="admins.adminmodel",
                    ),
                ),
                (
                    "reserved_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="client.clientmodel",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
