# Generated by Django 4.0 on 2023-09-07 14:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookmodel",
            name="inserted_date_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
