# Generated by Django 4.0 on 2023-09-07 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("book", "0001_initial"),
        ("author", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="authormodel",
            name="books",
            field=models.ManyToManyField(to="book.BookModel"),
        ),
    ]
