# Generated by Django 4.0 on 2023-09-05 13:05

import datetime

import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CLientModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=100)),
                ("lastname", models.CharField(max_length=100)),
                ("username", models.CharField(max_length=100, unique=True)),
                (
                    "email",
                    models.EmailField(blank=True, max_length=255, null=True, unique=True),
                ),
                (
                    "mobile",
                    models.CharField(
                        blank=True,
                        max_length=17,
                        validators=[utils.validators.mobile_validator],
                    ),
                ),
                (
                    "registration_date",
                    models.DateTimeField(
                        default=datetime.datetime(2023, 9, 5, 13, 5, 44, 980095)
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        default=datetime.datetime(2024, 9, 4, 13, 5, 44, 980140)
                    ),
                ),
            ],
        ),
    ]
