# Generated by Django 4.0 on 2023-09-07 14:20

import datetime

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientmodel",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 9, 6, 14, 20, 12, 413963)
            ),
        ),
        migrations.AlterField(
            model_name="clientmodel",
            name="mobile",
            field=models.CharField(
                blank=True,
                max_length=17,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                        regex="^\\+?1?\\d{9,15}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="clientmodel",
            name="registration_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 9, 7, 14, 20, 12, 413920)
            ),
        ),
    ]
