# Generated by Django 4.0 on 2023-09-07 14:24

import datetime

import django.utils.timezone
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0002_alter_clientmodel_expires_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientmodel",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 9, 6, 14, 24, 13, 505962, tzinfo=utc)
            ),
        ),
        migrations.AlterField(
            model_name="clientmodel",
            name="registration_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
